set_dehumidity:
  name: Set target dehumidity
  description: Set target dehumidity of climate device.
  target:
    entity:
      domain: climate
  fields:
    dehumidity:
      name: Humidity
      description: New target dehumidity for climate device.
      required: true
      selector:
        number:
          min: 10
          max: 50
          unit_of_measurement: "%"

trigger_air_cleaning_event:
  name: Trigger air cleaning event
  description: Trigger air cleaning event of climate device.
  target:
    entity:
      domain: climate
  fields:
    event:
      name: Event
      description: New air cleaning event for climate device.
      required: true
      selector:
        select:
          options:
            - label: "3 Hours"
              value: "3hour"
            - label: "24 Hours"
              value: "24hour"

cancel_air_cleaning_event:
  name: Cancel air cleaning event
  description: Cancel air cleaning event of climate device.
  target:
    entity:
      domain: climate

set_air_cleaning_mode:
  name: Set air cleaning mode
  description: Set the air cleaning mode of climate device.
  target:
    entity:
      domain: climate
  fields:
    mode:
      name: Mode
      description: New air cleaning mode.
      required: true
      selector:
        select:
          options:
            - label: "Off"
              value: 0
            - label: Constant Clean
              value: 1
            - label: Automatic
              value: 2

toggle_air_cleaning_mode:
  name: Toggle air cleaning mode
  description: Toggle the air cleaning mode of climate device.
  target:
    entity:
      domain: climate
  fields:
    mode:
      name: Mode
      description: New air cleaning mode.
      required: true
      selector:
        select:
          options:
            - label: "Off"
              value: 0
            - label: Constant Clean
              value: 1
            - label: Automatic
              value: 2

trigger_fresh_air_event:
  name: Trigger fresh air event
  description: Trigger fresh air event of climate device.
  target:
    entity:
      domain: climate
  fields:
    event:
      name: Event
      description: New fresh air event for climate device.
      required: true
      selector:
        select:
          options:
            - label: "3 Hours"
              value: "3hour"
            - label: "24 Hours"
              value: "24hour"

cancel_fresh_air_event:
  name: Cancel fresh air event
  description: Cancel fresh air event of climate device.
  target:
    entity:
      domain: climate

set_fresh_air_mode:
  name: Set fresh air mode
  description: Set the fresh air mode of climate device.
  target:
    entity:
      domain: climate
  fields:
    mode:
      name: Mode
      description: New fresh air mode.
      required: true
      selector:
        select:
          options:
            - label: "Off"
              value: 0
            - label: Automatic
              value: 1

toggle_fresh_air_mode:
  name: Toggle fresh air mode
  description: Toggle the fresh air mode of climate device.
  target:
    entity:
      domain: climate
  fields:
    mode:
      name: Mode
      description: New fresh air mode.
      required: true
      selector:
        select:
          options:
            - label: "Off"
              value: 0
            - label: Automatic
              value: 1
